# Generated by Django 5.0.5 on 2024-06-19 12:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_destination_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='end_date',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='start_date',
            new_name='check_out',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='num_people',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='available',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='price',
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='destination',
            name='price_adult',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='destination',
            name='price_child',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='destination',
            name='best_time_to_visit',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(upload_to='destinations/'),
        ),
    ]
