# Generated by Django 5.0.5 on 2024-06-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_rename_end_date_booking_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
